server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback: semua route diarahkan ke index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
